services:
  app2:
    image: traefik/whoami:latest
    hostname: app2
    ports:
      - 127.0.0.1:8282:80
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.app2.rule=Host(`app2.localhost`)"
      - "traefik.http.routers.app2.rule=PathPrefix(`/app2`)"
      - "traefik.http.services.app2.loadbalancer.server.port=80"
      - "traefik.docker.network=public_net"
    networks:
      - public_net
      - app2_net

networks:
  app2_net:
    name: app2_net
    driver: bridge
  # global compose file which is declaring this one
  # public_net:
  #   name: public_net
  #   external: true
      